name: Sync to Hugging Face hub

on:
  push:
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://Athu-devs:${{ env.HF_TOKEN }}@huggingface.co/spaces/Athu-dev/CS1-Group8 HEAD:main
